export default {
    searchForm: document.querySelector('.search-form'),
    searchFormInput: document.querySelector('.search-form__input'),
    containerWeatherToday: document.querySelector('.weather-today'),
    currentWeatherIcon: document.querySelector('.weather-today-icon'),
    cityName: document.querySelector('.current-name-city'),
    tempToday: document.querySelector('.current-temperature-today'),
    tempTodayMin: document.querySelector('.today-min'),
    tempTodayMax: document.querySelector('.today-max'),
    weatherContainer: document.querySelector('.weatherContainer'),
    onClickBtnOneDay:document.querySelector('.weather-one-day'),
    onClickBtnFiveDay:document.querySelector('.weather-5days'),
    preloader: document.querySelector('.preloader-con'),
    sunrise: document.querySelector('.sunrise__time'),
    sunset: document.querySelector('.sunset__time'),
}